defaults:
  source: http://localhost:9090
  from: now-1h
  to: now
  max_series: 10
variables:
  cluster: "eu"
  instance: "localhost"

up:
  query: up
  label: job

network-receive:
  query: rate(node_network_receive_bytes_total{device="wlp3s0"}[5m])
  unit: bytes
  label: device

network:
  unit: bytes
  label: device
  queries:
  - query: rate(node_network_receive_bytes_total{device="wlp3s0"}[5m])
  - query: -rate(node_network_transmit_bytes_total{device="wlp3s0"}[5m])
